### ISSUE TITLE
Add ability to build with Docker without Rake

### ISSUE THREAD

**Issue by halverneus** [randycoulman/jujube#17]
Add option to choose build option "Docker" to override default "rake full" behavior.

Original:

```yaml
    builders:
    - shell: rake full
```

New:

```yaml
    builders:
    - shell: docker build .
```

**Comment by randycoulman** [comment]
The `shell` builder takes whatever string you provide, so you should be able to do this with Jujube already. Feel free to re-open this if that's not the case.
